title: ''
logo: /opennms/user/assets/logo.png
author:
  name: Webmaster                           # Default author name
  email: 'webmaster@opennms.org'            # Default author email
  copyright: "Copyright 2016 The OpenNMS Group, Inc. All Rights Reserved."
social:
  - url: 'https://twitter.com/opennms/'
    icon: 'twitter'
  - url: 'https://www.youtube.com/user/opennms'
    icon: 'youtube'
  - url: 'https://plus.google.com/105624063334939417498'
    icon: 'google-plus'
  - url: 'blog.rss'
    icon: 'rss'
  - url: 'https://www.facebook.com/OpenNMS/'
    icon: 'facebook'
contact:
  address:
    - line: "220 Chatham Business Drive"
    - line: "Pittsboro, North Carolina 27312"
    - line: "United States"
othermenu:
  - text: "About"
    url: "about"
  - text: "Privacy Policy"
    url: "#"
  - text: "Contact"
    url: "contact"
quicklinks:
  - text: "Portfolio"
  - text: "About"
    url: "base_url:about"
  - text: "Services"
    url: "base_url:services"
  - text: "Archive"
    url: "base_url:archive"
  - text: "Blog"
    url: "base_url:blog"   
  - text: "Contact Us"
    url: "base_url:contact"          
taxonomies: [category,tag]                  # Arbitrary list of taxonomy types
blog:
  route: '/blog'                            # Route to blog
metadata:
    description: 'Project home page of OpenNMS - a java based network managememnt platform developed under the Open Source model'
summary:
  size: 300                                 # Maximum length of summary (characters)
routes:
  /something/else: '/blog/sample-3'         # Alias for /blog/sample-3
  /another/one/here: '/blog/sample-3'       # Another alias for /blog/sample-3
  /new/*: '/blog/*'                         # Wildcard any /new/my-page URL to /blog/my-page Route

header_options:
  arrows: 'true'                            # Create Next and previous button
  autoslide: 'false'                        # Auto slideshow mode
  autoslideHoverStop: 'false'               # Pause auto slideshow mode on mouseover
  interval: '2000'                          # The interval between each slide (Interval in millisecond)
  loop: 'false'                             # Infinite slideshow             
  transition : zoom                         # Set the animation kind (fade/slide/page/zoom)
  itemsForSlide: '0'                        # Wrap each 'n' item
  touch: 'true'                             # Set a native slide for touch device
  swipe : 'true'                            # Enable swipe for touch device

footer:
    description: "Java base network management platform developed under the Open Source model."
    contact_title: "Contact Info"
    links_title: "Quick Links"
    copyright_text: "Copyright 2016 The OpenNMS Group, Inc. All Rights Reserved."
    feedburner: ""   # Your feedburner id for Newsletter footer modul


