title: OpenNMS
author:
  name: OpenNMS Project
  email: 'webmaster@opennms.org'
metadata:
    description: 'OpenNMS is a Java based networm managemen platform developed under the Open Source model.'

credits: This website is made with <a href="http://getgrav.org/">Grav CMS</a> and it is powerd by <a href="http://diblas.net/themes/gravstrap-theme-to-start-grav-cms-site-with-bootstrap-support/">Gravstrap Theme</a> and <a href="http://diblas.net/plugins/use-bootstrap-elements-in-the-grav-cms-way/">Gravstrap Plugin</a>.
copyright: Joe Bloggs

gravstrap:
    navbar:
        # Add as many navbars as you need
        navbar1:
          id: bsnavbar
          # none, top, bottom
          fixed: top
          # none, centered, fluid
          centering: none
          inverted: true
          brand:
              text: OpenNMS
              image: brand.png
          items:
              menu0:
                  type: menu
                  alignment: center
                  # onepage: true
              menu1:
                  type: menu
                  alignment: right
                  items:
                      0:
                          url: http://twitter.com
                          type: link
                          icon_type: fontawesome
                          icon: twitter
                      1:
                          url: http://facebook.com
                          type: link
                          icon_type: fontawesome
                          icon: facebook
                      3:
                          url: http://my-rss.com
                          type: link
                          icon_type: fontawesome
                          icon: rss
