home:
  alias: '/project'

languages:
  supported:
    - en
    - de

pages:
  theme: opennms
  process:
    markdown: true
    twig: false
  markdown:
    extra: false  

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: false
  twig: false
  shutdown:
    close_connection: true
